---

- name: Collect IOS facts
  hosts: cisco-routers

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all

    - name: run sh ipv6 int br
      ios_command:
        commands:
          - show ipv6 int br
      register: show_result

    - name: Debug show_result
      when: show_result
      debug: var=show_result.stdout_lines
